org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
copyBuildJar=true

# Mod Attributes
mod_id=bondedan
mod_name=BondedAN
mod_version=1.0.0+1.21.4
mod_group=com.iamkaf.bondedan
mod_author=iamkaf
mod_description=A compat mod for Bonded and Advanced Netherite.
mod_license=MIT
mod_source_url=https://github.com/iamkaf/bonded-advanced-netherite-compat
mod_issue_url=https://github.com/iamkaf/mod-issues/issues
mod_update_url=https://raw.githubusercontent.com/iamkaf/modresources/main/update/bonded-advanced-netherite-compat.json
# "MATCH_VERSION" for a mod required on both sides, "IGNORE_SERVER_VERSION" for a server only mod, "IGNORE_ALL_VERSION" for a client only mod
mod_forge_display_test=MATCH_VERSION
# "*" for a mod loaded on both sides, "server" for a server only mod, "client" for a client only mod
mod_fabric_environment=*

# Minecraft properties
minecraft_version = 1.21.4
parchment_version = 1.21:2024.11.10

# Dependencies
amber_version = 2.1.0+1.21.4
architectury_api_version = 15.0.1
fabric_loader_version = 0.16.9
fabric_api_version = 0.110.5+1.21.4
neoforge_version = 21.4.47-beta
min_neoforge_version = 21.4.47-beta

bonded_version = 1.2.0+1.21.4
advanced_netherite_version = 2.2.2-mc1.21.4

# Development Utilities
emi_version = 1.1.13+1.21.1

# publishing
dry_run = false
curse_id = 1172101
modrinth_id = a5rNGaBT
release_type = release
game_versions = 1.21.4
mod_environment = both
mod_fabric_loaders = fabric
mod_modrinth_depends = amber,bonded,advanced-netherite
mod_curse_depends = amber-lib,bonded,advanced-netherite
